CREATE TABLE users (
	user_id VARCHAR(255) PRIMARY KEY,
	name VARCHAR(255),
	review_count INT,
	yelping_since DATE,
	useful INT,
	funny INT,
	cool INT,
	elite VARCHAR(255),
	fans INT,
	average_stars NUMERIC,
	compliment_hot INT,
	compliment_more INT,
	compliment_profile INT,
	compliment_cute INT,
	compliment_list INT,
	compliment_note INT,
	compliment_plain INT,
	compliment_cool INT,
	compliment_funny INT,
	compliment_writer INT,
	compliment_photos INT
)